#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            deb-systemd-invoke stop process-exporter.service >/dev/null || true
        fi
        ;;
esac

#DEBHELPER#

exit 0